### ISSUE TITLE
Can't enter warehouse

### ISSUE THREAD

**Issue by ger-pakon** [utkuali/esx_warehouse#4]
**Describe the bug**
When i try to enter the warehouse, nothing happens.

-> Server CLI: "SCRIPT ERROR: @esx_warehouse/server/main.lua:55: attempt to index a nil value"

**To Reproduce**
1. Go to 'Warehouse'
2. Press "E" to Enter

**Expected behavior**
Entering the warehouse.

**Screenshots**
No additional erros in the Ingame CLI. 

**Additional context**
Database entries set, user has both keys ( in the database).

**Comment by utkuali** [comment]
Looks like it cannot find the item "access_key" maybe? You should check if the item added to database and also you should check if that item (even if your character doesn't have one) shows up in your inventory database table, which is named user_inventory.

**Comment by ger-pakon** [comment]
Hey,

the user_iventory looks good.

```mysql
mysql> SELECT * FROM `user_inventory` WHERE `identifier` = 'steam:1100001002ec546' and item like '%key%'\G
*************************** 1. row ***************************
        id: 1267
identifier: steam:1100001002ec546
      item: warehouse_key
     count: 1
*************************** 2. row ***************************
        id: 1268
identifier: steam:1100001002ec546
      item: access_key
     count: 1
2 rows in set (0.00 sec)
```
Ah I see the error, the first entry was missing. I added it in runtime, but had to reload the ressource.

Suggestion: Check DB Entries on Startup and my drop a error message, if something needed is missing.

```mysql
mysql> SELECT * FROM `items` WHERE name like '%key%'\G
*************************** 1. row ***************************
      name: access_key
     label: Access Key
    weight: 0
      rare: 0
can_remove: 1
     limit: 1
*************************** 2. row ***************************
      name: warehouse_key
     label: Warehouse Key
    weight: 0
      rare: 0
can_remove: 1
     limit: 1
2 rows in set (0.00 sec)
```
